#!/usr/bin/env bash
# Usage: ./1-world_wide_web <domain> <subdomain>
# Display information about subdomains.

domain_information () {
    expected_ip=""
    case "$2" in
        "www") expected_ip="35.153.16.72" ;;
        "lb-01") expected_ip="54.237.117.138" ;;
        "web-01") expected_ip="100.26.216.97" ;;
        "web-02") expected_ip="203.0.113.0" ;;
        # Add more cases for other subdomains if needed
    esac

    line=$(dig "$2"."$1" | grep -A1 'ANSWER SECTION:' | tr '\t' '\n' | tail -2 | tr '\n' ' ')
    echo "$2 $line" | awk '{print "The subdomain " $1 " is a " $2 " record and points to " $3}'

    if [ "$expected_ip" != "" ]; then
        echo "Expected IP address for $2: $expected_ip"
    fi
}

if [ "$#" == 1 ]; then
  domain_information "$1" "www"
  domain_information "$1" "lb-01"
  domain_information "$1" "web-01"
  domain_information "$1" "web-02"
elif [ "$#" == 2 ]; then
  domain_information "$1" "$2"
fi
