#!/usr/bin/env bash
# bash: script install and configure Nginx web server
#       and redirects traffic:

sudo apt-get update -y
sudo apt-get install -y nginx

# configure Nginx
sudo ufw allow 'Nginx HTTP'
sudo sed -i 's/80 default_server/80/' /etc/nginx/sites-available/default
sudo service nginx restart

# create index.html file served out by server:
echo 'Hello World!' | sudo tee /var/www/html/index.html > /dev/null

# configure the redirection
sudo sed -i '/location \/ {/a \    location \/redirect_me { return 301 https:\/\/www.youtube.com\/watch?v=QH2-TGUlwu4; }' /etc/nginx/sites-available/default
sudo service nginx restart
